
export type EnterpriseRole = 'SYSTEM_ADMIN' | 'SYSTEM_STAFF';

export interface AuditLogEntry {
  id: string;
  timestamp: string;
  user: string;
  action: 'Created' | 'Modified' | 'Deleted' | 'Status Change' | 'Cancelled';
  changes: {
    field: string;
    oldValue: any;
    newValue: any;
  }[];
  reason?: string;
}

export enum TabView {
  DASHBOARD = 'DASHBOARD',
  LEADS = 'LEADS',
  CLIENTS = 'CLIENTS',
  VENDORS = 'VENDORS',
  INVENTORY = 'INVENTORY',
  BILLING = 'BILLING',
  QUOTES = 'QUOTES',
  PO_BUILDER = 'PO_BUILDER',
  SUPPLIER_PO = 'SUPPLIER_PO',
  SERVICE_ORDERS = 'SERVICE_ORDERS',
  SERVICE_REPORTS = 'SERVICE_REPORTS',
  INSTALLATION_REPORTS = 'INSTALLATION_REPORTS',
  DELIVERY = 'DELIVERY',
  TASKS = 'TASKS',
  ATTENDANCE = 'ATTENDANCE',
  EXPENSES = 'EXPENSES',
  PERFORMANCE = 'PERFORMANCE',
  HR = 'HR',
  PROFILE = 'PROFILE',
  REPORTS = 'REPORTS',
  CATALOG = 'CATALOG',
  LOGS = 'LOGS',
  ARCHIVE = 'ARCHIVE',
  PAYROLL = 'PAYROLL',
  CONFIG = 'CONFIG',
  PURCHASE_REGISTER = 'PURCHASE_REGISTER',
  ACCOUNTING = 'ACCOUNTING',
  COMPLIANCE = 'COMPLIANCE',
  COMPANIES = 'COMPANIES'
}

export enum LeadStatus {
  NEW = 'New',
  ON_PROCESS = 'On process',
  WON = 'Won',
  LOST = 'Lost'
}

export interface FollowUp {
  id: string;
  date: string;
  type: 'Call' | 'Meeting' | 'WhatsApp';
  notes: string;
  status: 'Pending' | 'Completed';
}

export interface Lead {
  id: string;
  name: string;
  hospital: string;
  source: string;
  status: LeadStatus;
  value: number;
  lastContact: string;
  productInterest: string;
  phone?: string;
  email?: string;
  address?: string;
  followUps: FollowUp[];
  contactPerson?: string;
  salesTakenBy?: string;
}

export interface Client {
  id: string;
  name: string;
  hospital?: string;
  address: string;
  gstin?: string;
  email?: string;
  phone?: string;
  cinNo?: string;
  panNo?: string;
  dlNo?: string;
  udyamNo?: string;
  status?: 'Draft' | 'Finalized';
}

export interface Vendor {
  id: string;
  name: string;
  address: string;
  contactPerson?: string;
  gstin?: string;
  email?: string;
  phone?: string;
  cinNo?: string;
  panNo?: string;
  dlNo?: string;
  udyamNo?: string;
  status?: 'Draft' | 'Finalized';
  procurementVolume?: number;
}


export interface ProductVendorInfo {
  vendorId: string;
  vendorName: string;
  purchasePrice: number;
}

export interface Product {
  id: string;
  name: string;
  category: 'Equipment' | 'Consumable' | 'Spare Part' | 'Pipe Line' | 'Furniture';
  sku: string;
  stock: number;
  unit: string;
  purchasePrice: number;
  sellingPrice: number;
  minLevel: number;
  location: string;
  hsn?: string;
  taxRate?: number;
  model?: string;
  description?: string;
  specs?: Record<string, string>;
  supplier?: string;
  vendors?: ProductVendorInfo[];
  lastRestocked?: string;
  price?: number;
  isBatchTracked?: boolean;
  reorderLevel?: number;
  godown?: string;
}

// --- NEW ACCOUNTING & COMPLIANCE TYPES ---

export type VoucherType = 'Sales' | 'Purchase' | 'Payment' | 'Receipt' | 'Contra' | 'Journal' | 'Debit Note' | 'Credit Note';

export interface AccountGroup {
  id: string;
  name: string;
  parentGroupId?: string;
  type: 'Asset' | 'Liability' | 'Equity' | 'Revenue' | 'Expense';
}

export interface Ledger {
  id: string;
  name: string;
  alias?: string;
  groupId: string;
  openingBalance: number;
  currentBalance: number;
  mailingName?: string;
  address?: string;
  gstin?: string;
  pan?: string;
  contactPerson?: string;
  phone?: string;
  mobile?: string;
  email?: string;
  creditLimit?: number;
  creditDays?: number;
  bankAccountNo?: string;
  ifscCode?: string;
  costCentreApplicable?: boolean;
  taxRate?: number;
  hsnSacCode?: string;
  isActive?: boolean;
  linkedEntityType?: 'CRM_CUSTOMER' | 'VENDOR' | 'EMPLOYEE' | 'BANK';
  linkedEntityId?: string;
  description?: string;
}

export interface LedgerEntry {
  id: string;
  ledgerId: string;
  ledgerName: string;
  debit: number;
  credit: number;
  narration?: string;
  costCentreId?: string;
  autoGenerated?: boolean;
}

export interface CostCentre {
  id: string;
  name: string;
  description?: string;
}

export interface FixedAsset {
  id: string;
  name: string;
  ledgerId: string;
  purchaseDate: string;
  purchaseCost: number;
  usefulLifeYears: number;
  salvageValue: number;
  depreciationMethod: 'SLM' | 'WDV';
  accumulatedDepreciation: number;
  netBookValue: number;
  status: 'Active' | 'Disposed' | 'Fully Depreciated';
  disposalDate?: string;
}

export interface DepreciationScheduleEntry {
  id: string;
  assetId: string;
  date: string;
  amount: number;
  accumulatedDepreciation: number;
  netBookValue: number;
}

export interface BillSettlement {
  invoiceId: string;
  invoiceNumber: string;
  voucherId: string;
  amount: number;
  date: string;
}

export type VoucherStatus = 'DRAFT' | 'PENDING_APPROVAL' | 'POSTED' | 'REJECTED';

export interface AccountingVoucher {
  id: string;
  voucherNumber: string;
  date: string;
  type: VoucherType;
  entries: LedgerEntry[];
  narration: string;
  referenceId?: string;
  referenceNumber?: string;
  totalAmount: number;
  settlements?: BillSettlement[];
  createdBy: string;
  createdOn?: string;
  editHistory?: AuditLogEntry[];
  bankReconciliationDate?: string;
  tdsRate?: number;
  tdsSection?: string;
  costCentreId?: string;
  chequeNo?: string;
  chequeDate?: string;
  chequeBank?: string;
  status?: VoucherStatus;
  rejectedReason?: string;
  approvedBy?: string;
  placeOfSupply?: string;
  refVoucherType?: VoucherType;
  gstDetails?: {
    taxableValue: number;
    cgst: number;
    sgst: number;
    igst: number;
    totalGst: number;
  };
}

export interface PeriodLock {
  lockUpTo: string;
  lockedBy: string;
  lockedOn: string;
  overrideRequires: 'DIRECTOR';
}

export interface GSTConfig {
  gstin: string;
  registrationDate: string;
  registrationType: 'Regular' | 'Composition' | 'Unregistered';
  filingFrequency: 'Monthly' | 'Quarterly';
  eInvoiceApplicable: boolean;
  eWayBillApplicable: boolean;
}

export interface HSNMaster {
  code: string;
  description: string;
  gstRate: number;
}

export interface GSTR1Section {
  section: string;
  invoices: number;
  taxableValue: number;
  totalGst: number;
  status: 'Ready' | 'Pending' | 'N/A';
}

export interface GoToItem {
  id: string;
  label: string;
  type: 'screen' | 'ledger' | 'voucher' | 'report';
  action: () => void;
  shortcut?: string;
}

export interface CostCentreAllocation {
  costCentreId: string;
  costCentreName: string;
  amount: number;
}

export interface BankStatementEntry {
  id: string;
  date: string;
  description: string;
  amount: number;
  type: 'Debit' | 'Credit';
  reference?: string;
  isMatched: boolean;
  matchedVoucherId?: string;
}

export interface AutoVoucherDraft {
  statementEntryId: string;
  date: string;
  description: string;
  amount: number;
  txType: 'Debit' | 'Credit';
  voucherType: VoucherType;
  drLedgerId: string;
  drLedgerName: string;
  crLedgerId: string;
  crLedgerName: string;
  narration: string;
  skip: boolean;
  ruleLabel: string;
}

export interface BankRule {
  id: string;
  pattern: string;
  txType: 'Debit' | 'Credit' | 'Both';
  voucherType: VoucherType;
  drLedgerId: string;
  drLedgerName: string;
  crLedgerId: string;
  crLedgerName: string;
  ruleLabel: string;
}


export interface StockTransfer {
  id: string;
  date: string;
  productId: string;
  productName: string;
  fromLocation: string;
  toLocation: string;
  quantity: number;
  reference?: string;
  createdBy: string;
}

export interface StatutoryDeduction {
  id: string;
  employeeId: string;
  monthId: string; // YYYY-MM
  pf: number;
  esi: number;
  professionalTax: number;
  otherDeductions: number;
  totalDeductions: number;
  netSalary: number;
}

export interface TdsTcsRecord {
  id: string;
  date: string;
  ledgerId: string;
  ledgerName: string;
  type: 'TDS' | 'TCS';
  section: string;
  taxableAmount: number;
  taxRate: number;
  taxAmount: number;
  referenceVoucherId: string;
}

export interface InvoiceItem {
  id: string;
  description: string;
  hsn?: string;
  quantity: number;
  unitPrice: number;
  taxRate: number;
  cgstRate?: number;
  sgstRate?: number;
  igstRate?: number;
  amount: number;
  gstValue: number;
  priceWithGst: number;
  model?: string;
  features?: string;
  unit?: string;
}

export interface Invoice {
  id: string;
  invoiceNumber: string;
  date: string;
  items: InvoiceItem[];
  status: 'Pending' | 'Paid' | 'Completed' | 'Draft' | 'Finalized' | 'Cancelled';
  customerName: string;
  customerHospital?: string;
  customerAddress?: string;
  customerGstin?: string;
  subtotal: number;
  taxTotal: number;
  grandTotal: number;
  isRoundOff?: boolean;
  roundOff?: number;
  incentivePercentage?: number;
  documentType?: 'Invoice' | 'PO' | 'Quotation' | 'SupplierPO' | 'ServiceOrder' | 'ServiceReport' | 'InstallationReport';
  createdBy?: string;
  closedBy?: string;
  smcpoNumber?: string;
  deliveryTime?: string;
  specialNote?: string;
  cpoNumber?: string;
  cpoDate?: string;
  bankDetails?: string;
  selectedBank?: BankDetails;
  deliveryAddress?: string;
  bankAndBranch?: string;
  accountNo?: string;
  paymentMethod?: 'Bank Transfer' | 'NEFT' | 'RTGS' | 'Cheque' | 'Cash' | 'UPI';
  advanceAmount?: number;
  advanceDate?: string;
  discount?: number;
  subject?: string;
  phone?: string;
  email?: string;
  contactPerson?: string;
  freightAmount?: number;
  freightTaxRate?: number;
  paymentTerms?: string;
  deliveryTerms?: string;
  buyerName?: string;
  buyerAddress?: string;
  buyerGstin?: string;
  warrantyTerms?: string;
  dispatchedThrough?: string;
  paidAmount?: number;
  paymentDate?: string;
  paymentBank?: string;
  sellerProfile?: CompanyProfile;
  remarks?: string;
  freight?: string;
  equipmentName?: string;
  model?: string;
  serialNumber?: string;
  machineStatus?: string;
  engineerName?: string;
  problemReported?: string;
  department?: string;
  visitType?: string;
  priority?: 'Urgent' | 'High' | 'Medium' | 'Low';
  expectedResolutionDate?: string;
  machineLocation?: string;
  balanceDue?: number;
  editHistory?: AuditLogEntry[];
}

export interface StockMovement {
  id: string;
  productId: string;
  productName: string;
  type: 'In' | 'Out';
  quantity: number;
  date: string;
  reference: string;
  purpose: 'Restock' | 'Sale' | 'Demo';
  batchId?: string;
}

export interface StockBatch {
  id: string;
  productId: string;
  batchNo: string;
  expiryDate: string;
  quantity: number;
  createdDate: string;
}

export interface ExpenseRecord {
  id: string;
  employeeName: string;
  date: string;
  category: 'Travel' | 'Food' | 'Lodging' | 'Supplies' | 'Other';
  amount: number;
  description: string;
  status: 'Pending' | 'Approved' | 'Rejected';
  receiptUrl?: string;
  rejectionReason?: string;
  editHistory?: AuditLogEntry[];
}

export interface Employee {
  id: string;
  name: string;
  role: EnterpriseRole;
  department: string;
  email: string;
  phone?: string;
  joinDate?: string;
  baseSalary?: number;
  status: 'Active' | 'On Leave';
  permissions: Record<string, 'Admin' | 'Employee'>;
  password?: string;
  isLoginEnabled: boolean;
  lastSeenWinnerMonth?: string; // Format: YYYY-MM
  hideFromLeaderboard?: boolean;
}

export interface UserStats {
  points: number;
  tasksCompleted: number;
  attendanceStreak: number;
  salesRevenue: number;
}

export interface AttendanceRecord {
  id: string;
  userId: string;
  userName: string;
  date: string; // ISO date string (YYYY-MM-DD)
  checkInTime: string | null;
  checkOutTime: string | null;
  totalWorkedMs: number;
  lastSessionStartTime: string | null;
  status: 'CheckedIn' | 'Paused' | 'Completed' | 'OnLeave';
  leaveReason?: string;
  workMode: 'Office' | 'Field' | 'Remote';
  lat?: number;
  lng?: number;
  accuracy?: number;
  editHistory?: {
    editedAt: string;
    editedBy: string;
    reason: string;
    prevIn: string | null;
    prevOut: string | null;
  }[];
}

export interface PointHistory {
  id: string;
  date: string;
  points: number;
  category: 'Task' | 'Attendance' | 'Sales' | 'Lead';
  description: string;
  userId: string;
}

export interface AppNotification {
  id: string;
  title: string;
  message: string;
  time: string;
  type: 'alert' | 'warning' | 'success' | 'info';
  read: boolean;
}

export interface MonthlyWinner {
  id: string;
  monthId: string; // YYYY-MM
  userId: string;
  userName: string;
  points: number;
}

export interface CompanyProfile {
  id: string;
  companyName: string;
  name?: string; // Alias for companyName, used in legacy PDFService fallbacks
  address: string;
  gstin?: string;
  email?: string;
  phone?: string;
  bankName: string;
  accountNo: string;
  branchIfsc: string;
  cinNo?: string;
  panNo?: string;
}

export interface BankDetails {
  id: string;
  bankName: string;
  accountNo: string;
  branchIfsc: string;
  accountType?: string;
  isDefault?: boolean;
}

export interface SystemSettings {
  id: string;
  lastResetMonth: string; // Format: YYYY-MM
  financialYear: string; // Format: 26-27
  bankDetails?: BankDetails[];
  companyProfiles?: CompanyProfile[];
}

export interface TaskLog {
  id: string;
  user: string;
  action: string;
  timestamp: string;
}

export interface RescheduleRequest {
  newDate: string;
  reason: string;
  status: 'Pending' | 'Approved' | 'Rejected';
  requestedBy: string;
  requestedAt: string;
  responseNote?: string;
}

export interface Task {
  id: string;
  title: string;
  description: string;
  assignedTo: string;
  priority: 'Low' | 'Medium' | 'High';
  status: 'To Do' | 'In Progress' | 'Review' | 'Done';
  dueDate: string;
  locationName?: string;
  submittedBy?: string;
  pointsAwarded?: boolean;
  handoffChain: string[];
  handoffNotes?: string;
  subTasks?: any[];
  logs?: TaskLog[];
  rescheduleRequest?: RescheduleRequest;
}

export interface ServiceTicket {
  id: string;
  customer: string;
  equipment: string;
  issue: string;
  priority: 'Low' | 'Medium' | 'High';
  status: 'Open' | 'In Progress' | 'Resolved';
  assignedTo: string;
  dueDate: string;
}

export interface AMCReminder {
  id: string;
  customer: string;
  equipment: string;
  expiryDate: string;
}

export interface ServiceReportItem {
  id: string;
  description: string;
  quantity: number;
  unitPrice: number;
  amount: number;
}

export interface ServiceReport {
  id: string;
  reportNumber: string;
  date: string;
  customerName: string;
  equipmentName: string;
  problemReported: string;
  actionTaken: string;
  engineerName: string;
  status: 'Draft' | 'Completed';
  itemsUsed?: ServiceReportItem[];
  documentType?: string;
  serialNumber?: string;
  customerHospital?: string;
  customerAddress?: string;
  office?: string;
  time?: string;
  machineStatus?: 'Warranty' | 'Out Of Warranty' | 'AMC';
  softwareVersion?: string;
  engineerObservations?: string;
  poWoNumber?: string;
  actionHardware?: string;
  actionOperational?: string;
  actionSoftware?: string;
  pastBalance?: number;
  visitCharges?: number;
  sparesCharges?: number;
  amountReceived?: number;
  memoNumber?: string;
  queriesRemarks?: string;
  smirNo?: string;
  installationOf?: string;
  trainedPersons?: string;
  sellerProfile?: CompanyProfile;
  phone?: string;
  model?: string;
  department?: string;
  visitType?: string;
  referenceOrderNumber?: string;
  referenceOrderId?: string;
}

export interface SupportMessage {
  id: string;
  sender: string;
  text: string;
  timestamp: string;
  isAdmin: boolean;
}

export interface SupportTicket {
  id: string;
  subject: string;
  customerName: string;
  customerEmail: string;
  priority: 'Low' | 'Medium' | 'High' | 'Urgent';
  status: 'Open' | 'In Progress' | 'Resolved' | 'Closed';
  category: 'Technical' | 'Billing' | 'Sales' | 'General';
  createdAt: string;
  updatedAt: string;
  messages: SupportMessage[];
}

export interface UserProfile {
  name: string;
  role: string;
  email: string;
  phone: string;
  department: string;
  location: string;
  bio: string;
  notifications: {
    email: boolean;
    sms: boolean;
    push: boolean;
  };
}

export interface ChallanItem {
  id: string;
  description: string;
  quantity: number;
  unit?: string;
  remarks?: string;
}

export interface DeliveryChallan {
  id: string;
  challanNumber: string;
  date: string;
  customerName: string;
  customerAddress: string;
  items: ChallanItem[];
  status: 'Draft' | 'Dispatched';
  subject?: string;
  terms?: string;
  remarks?: string;
  sellerProfile?: CompanyProfile;
  createdBy?: string;
  invoiceId?: string;
}

export interface Holiday {
  id: string;
  date: string; // YYYY-MM-DD
  name: string;
}

export interface LogEntry {
  id: string;
  timestamp: string;
  userName: string;
  userRole: string;
  action: string;
  details: string;
  category: 'Attendance' | 'Inventory' | 'Leads' | 'Auth' | 'System' | 'Tasks' | 'Billing' | 'Accounting';
  beforeValues?: any;
  afterValues?: any;
}

export interface LeaveRequest {
  id: string;
  userId: string;
  userName: string;
  startDate: string; // YYYY-MM-DD
  endDate: string; // YYYY-MM-DD
  reason: string;
  status: 'Pending' | 'Approved' | 'Rejected';
  appliedOn: string; // ISO timestamp
  adminFeedback?: string;
}

export interface PurchaseItem {
  id: string;
  equipmentName: string;
  rate: number;
  qty: number;
  unit?: string;
  gstPercent?: number; // Added for convenience
  cgstPercent?: number;
  sgstPercent?: number;
  igstPercent?: number;
  totalGst: number;
  totalIgst: number;
  total: number;
}

export interface PurchaseRecord {
  id: string;
  dateSupply: string;
  materialReceivedDate: string;
  supplier: string;
  equipmentName?: string;
  invoiceNo: string;
  rate?: number;
  qty?: number;
  unit?: string;
  gstPercent?: number; // Added for legacy support/convenience
  packingCharges: number;
  forwardingCharges: number;
  freightCharges: number;
  freightGstPercent?: number;
  cgstPercent?: number;
  sgstPercent?: number;
  igstPercent?: number;
  totalGst: number;
  totalIgst: number;
  total: number;
  isRoundOff?: boolean;
  roundOff?: number;
  createdBy?: string;
  items?: PurchaseItem[];
  paidAmount?: number;
  status?: 'Pending' | 'Paid' | 'Completed' | 'Draft' | 'Finalized' | 'Cancelled';
}

