import React, { useState, useMemo, useEffect, useRef } from 'react';
import { useData } from './DataContext';
import { VoucherType, Ledger, AccountingVoucher, LedgerEntry, AccountGroup, GSTR1Section, GoToItem } from '../types';

type TallyScreen = 'gateway' | 'voucher_pay' | 'voucher_rec' | 'voucher_jnl' | 'voucher_sls' | 'voucher_pur' | 'contra' | 'daybook' | 'bs' | 'pl' | 'tb' | 'outstanding' | 'gst' | 'shortcuts';
type VoucherMode = 'Payment' | 'Receipt' | 'Contra' | 'Journal' | 'Sales' | 'Purchase' | 'Debit Note' | 'Credit Note';

const genId = () => `${Date.now()}-${Math.random().toString(36).slice(2,6)}`;
const fmt = (n: number) => Math.abs(n).toLocaleString('en-IN', { maximumFractionDigits: 2, minimumFractionDigits: 2 });
const getFY = () => { const d = new Date(); const y = d.getFullYear(); return d.getMonth() >= 3 ? `${y}-${(y+1).toString().slice(2)}` : `${(y-1)}-${y.toString().slice(2)}`; };
const today = () => new Date().toISOString().split('T')[0];
const fmtDate = (d: string) => { if (!d) return ''; const p = d.split('-'); return `${p[2]}/${p[1]}/${p[0].slice(2)}`; };

const shortKeys: Record<VoucherMode, string> = {
  Payment: 'F5', Receipt: 'F6', Contra: 'F4', Journal: 'F7',
  Sales: 'F8', Purchase: 'F9', 'Debit Note': 'Ctrl+F9', 'Credit Note': 'Ctrl+F8',
};

interface VFState {
  type: VoucherMode; date: string; accountName: string; accountId: string;
  entries: LedgerEntry[]; narration: string; refNo: string; chequeNo: string; chequeDate: string;
}

interface AccountingModuleProps { userRole?: 'Admin' | 'Employee'; }

export const AccountingModule: React.FC<AccountingModuleProps> = ({ userRole }) => {
  const isAdmin = userRole === 'Admin';
  const { ledgers = [], vouchers = [], accountGroups = [], invoices = [], purchaseRecords = [],
    addLedger, updateLedger, removeLedger, addAccountGroup, removeAccountGroup, updateAccountGroup,
    reverseVoucher, updateVoucher, postToLedger, addNotification, addCostCentre, updateCostCentre, removeCostCentre,
    uploadBankStatement, autoMatchBankEntries, ensurePartyLedger, currentUser } = useData();

  const [screen, setScreen] = useState<TallyScreen>('gateway');
  const [showGoto, setShowGoto] = useState(false);
  const [gotoQ, setGotoQ] = useState('');
  const [statusMsg, setStatusMsg] = useState('Ready');
  const gotoRef = useRef<HTMLInputElement>(null);
  const [daybookDate, setDaybookDate] = useState(today());
  const [selLedger, setSelLedger] = useState<Ledger | null>(null);
  const [selVoucher, setSelVoucher] = useState<AccountingVoucher | null>(null);
  const [searchQ, setSearchQ] = useState('');

  // Voucher form
  const vfInit: VFState = {
    type: 'Payment', date: today(), accountName: '', accountId: '',
    entries: [{ id: genId(), ledgerId: '', ledgerName: '', debit: 0, credit: 0 },
              { id: genId(), ledgerId: '', ledgerName: '', debit: 0, credit: 0 }],
    narration: '', refNo: '', chequeNo: '', chequeDate: '',
  };
  const [vf, setVf] = useState<VFState>({...vfInit});
  const [showVf, setShowVf] = useState(false);
  const [diff, setDiff] = useState(0);

  const resetVf = (type: VoucherMode) => {
    setVf({ ...vfInit, type, date: today() });
    setShowVf(true);
    setDiff(0);
    setStatusMsg(`${type} Voucher`);
  };

  const updateEntry = (id: string, u: Partial<LedgerEntry>) =>
    setVf(p => ({ ...p, entries: p.entries.map(e => e.id === id ? { ...e, ...u } : e) }));
  const addEntry = () => setVf(p => ({ ...p, entries: [...p.entries, { id: genId(), ledgerId: '', ledgerName: '', debit: 0, credit: 0 }] }));
  const delEntry = (id: string) => setVf(p => ({ ...p, entries: p.entries.filter(e => e.id !== id) }));
  const td = useMemo(() => vf.entries.reduce((s, e) => s + Number(e.debit || 0), 0), [vf.entries]);
  const tc = useMemo(() => vf.entries.reduce((s, e) => s + Number(e.credit || 0), 0), [vf.entries]);
  useEffect(() => { setDiff(td - tc); }, [td, tc]);

  const handleSaveVoucher = async () => {
    if (td !== tc) { addNotification('Unbalanced', 'Debit must equal Credit.', 'alert'); return; }
    if (td === 0) { addNotification('Invalid', 'Amount cannot be zero.', 'alert'); return; }
    await postToLedger({
      type: vf.type as unknown as VoucherType,
      date: vf.date,
      entries: vf.entries.map(({ autoGenerated, ...r }) => r),
      narration: vf.narration,
      totalAmount: td,
      referenceNumber: vf.refNo || undefined,
      chequeNo: vf.chequeNo || undefined,
      chequeDate: vf.chequeDate || undefined,
    });
    addNotification('Voucher Posted', `${vf.type} saved.`, 'success');
    setShowVf(false);
    setScreen('gateway');
    setStatusMsg('Gateway of Accounts');
  };

  // Computed
  const groupMap = useMemo(() => new Map(accountGroups.map(g => [g.id, g])), [accountGroups]);
  const ledgersByGid = useMemo(() => { const m = new Map<string, Ledger[]>(); ledgers.forEach(l => { const a = m.get(l.groupId) || []; a.push(l); m.set(l.groupId, a); }); return m; }, [ledgers]);

  const stats = useMemo(() => {
    const isBank = (g: AccountGroup | undefined) => g?.name === 'Cash-in-Hand' || g?.name === 'Bank Accounts' || g?.name === 'Bank Accounts' || g?.id === 'GRP-CASH' || g?.id === 'GRP-BANK';
    const isDr = (g: AccountGroup | undefined) => g?.name === 'Sundry Debtors' || g?.id === 'GRP-DEBTORS';
    const isCr = (g: AccountGroup | undefined) => g?.name === 'Sundry Creditors' || g?.id === 'GRP-CREDITORS';
    const ids = (fn: (g: AccountGroup | undefined) => boolean) => ledgers.filter(l => fn(groupMap.get(l.groupId))).map(l => l.id);
    const sum = (ids: string[]) => ids.reduce((s, id) => s + (ledgers.find(l => l.id === id)?.currentBalance || 0), 0);
    return { cashBank: sum(ids(isBank)), debtors: sum(ids(isDr)), creditors: sum(ids(isCr)) };
  }, [ledgers, groupMap]);

  // GoTo items
  const goToItems: GoToItem[] = useMemo(() => [
    { id: 'gt0', label: 'Gateway of Accounts', type: 'screen', action: () => setScreen('gateway'), shortcut: 'F1' },
    { id: 'gt1', label: 'Payment Voucher', type: 'screen', action: () => resetVf('Payment'), shortcut: 'F5' },
    { id: 'gt2', label: 'Receipt Voucher', type: 'screen', action: () => resetVf('Receipt'), shortcut: 'F6' },
    { id: 'gt3', label: 'Journal', type: 'screen', action: () => resetVf('Journal'), shortcut: 'F7' },
    { id: 'gt4', label: 'Sales Invoice', type: 'screen', action: () => resetVf('Sales'), shortcut: 'F8' },
    { id: 'gt5', label: 'Purchase Invoice', type: 'screen', action: () => resetVf('Purchase'), shortcut: 'F9' },
    { id: 'gt6', label: 'Day Book', type: 'screen', action: () => setScreen('daybook') },
    { id: 'gt7', label: 'Balance Sheet', type: 'screen', action: () => setScreen('bs') },
    { id: 'gt8', label: 'Profit & Loss', type: 'screen', action: () => setScreen('pl') },
    { id: 'gt9', label: 'Trial Balance', type: 'screen', action: () => setScreen('tb') },
    { id: 'gt10', label: 'Outstanding', type: 'screen', action: () => setScreen('outstanding') },
    { id: 'gt11', label: 'GST Reports', type: 'screen', action: () => setScreen('gst') },
    { id: 'gt12', label: 'Shortcut Keys', type: 'screen', action: () => setScreen('shortcuts') },
    ...ledgers.slice(0, 15).map(l => ({ id: `gl-${l.id}`, label: `Ledger: ${l.name}`, type: 'ledger' as const, action: () => { setSelLedger(l); }, shortcut: '' })),
  ], [ledgers]);

  const filteredGoto = useMemo(() => {
    const q = gotoQ.toLowerCase();
    return goToItems.filter(i => !q || i.label.toLowerCase().includes(q) || i.type.includes(q) || (i.shortcut || '').toLowerCase().includes(q));
  }, [gotoQ, goToItems]);

  // Keyboard handler — all shortcuts must be working
  useEffect(() => {
    const h = (e: KeyboardEvent) => {
      // ─── GO TO OVERLAY ───
      if (showGoto) {
        if (e.key === 'Escape') { e.preventDefault(); setShowGoto(false); setGotoQ(''); return; }
        if (e.key === 'Enter' && filteredGoto.length > 0) { e.preventDefault(); filteredGoto[0].action(); setShowGoto(false); setGotoQ(''); return; }
        return;
      }

      // ─── GLOBAL SHORTCUTS (always available) ───
      if (e.altKey && (e.key === 'g' || e.key === 'G')) { e.preventDefault(); setShowGoto(true); setTimeout(() => gotoRef.current?.focus(), 50); return; }
      if (e.key === 'F1') { e.preventDefault(); setShowVf(false); setScreen('gateway'); setStatusMsg('Gateway of Accounts'); return; }
      if (e.key === 'F3') { e.preventDefault(); addNotification('Company Info', 'Sreemeditec — current company.', 'info'); return; }
      if (e.key === 'F11') { e.preventDefault(); addNotification('Features', 'F11 Features configuration — available in full version.', 'info'); return; }
      if (e.key === 'F12') { e.preventDefault(); addNotification('Configure', 'F12 Configuration — available in full version.', 'info'); return; }

      // ─── F2: CHANGE DATE ON ANY SCREEN ───
      if (e.key === 'F2') {
        e.preventDefault();
        if (showVf) {
          const d = prompt('Voucher date (YYYY-MM-DD):', vf.date);
          if (d) setVf(p => ({...p, date: d}));
        } else {
          const d = prompt('Change date (YYYY-MM-DD):', daybookDate);
          if (d) setDaybookDate(d);
        }
        return;
      }

      // ─── ALT+F1 / ALT+F2: Report view toggle / period ───
      if (e.altKey && e.key === 'F1') { e.preventDefault(); addNotification('View', 'Detailed view toggled.', 'success'); return; }
      if (e.altKey && e.key === 'F2') { e.preventDefault(); const d = prompt('Change period (YYYY-MM-DD):', daybookDate); if (d) setDaybookDate(d); return; }

      // ─── VOUCHER SHORTCUTS (open voucher from any screen) ───
      if (e.key === 'F4') { e.preventDefault(); resetVf('Contra'); return; }
      if (e.key === 'F5') { e.preventDefault(); resetVf('Payment'); return; }
      if (e.key === 'F6') { e.preventDefault(); resetVf('Receipt'); return; }
      if (e.key === 'F7') { e.preventDefault(); resetVf('Journal'); return; }
      if (e.key === 'F8' && !e.ctrlKey) { e.preventDefault(); resetVf('Sales'); return; }
      if (e.key === 'F9' && !e.ctrlKey) { e.preventDefault(); resetVf('Purchase'); return; }
      if (e.ctrlKey && e.key === 'F8') { e.preventDefault(); resetVf('Credit Note'); return; }
      if (e.ctrlKey && e.key === 'F9') { e.preventDefault(); resetVf('Debit Note'); return; }

      // ─── NAVIGATION ───
      if (e.key === 'Escape') {
        if (showVf) {
          if (window.confirm('Quit without saving?')) { setShowVf(false); setScreen('gateway'); setStatusMsg('Gateway of Accounts'); }
          return;
        }
        if (screen !== 'gateway') { e.preventDefault(); setScreen('gateway'); setStatusMsg('Gateway of Accounts'); return; }
      }

      // ─── VOUCHER-FORM-SPECIFIC SHORTCUTS ───
      if (showVf) {
        // Tab / Enter navigation
        if ((e.key === 'Enter' || e.key === 'Tab') && !e.ctrlKey && !e.altKey) {
            const active = document.activeElement;
            if (active && (active.tagName === 'INPUT' || active.tagName === 'SELECT' || active.tagName === 'TEXTAREA')) {
                if (e.key === 'Enter') {
                    e.preventDefault(); // prevent form submit or default enter
                    const focusables = Array.from(document.querySelectorAll('input, select, textarea, button'));
                    const index = focusables.indexOf(active);
                    if (index > -1) {
                        const next = focusables[index + (e.shiftKey ? -1 : 1)];
                        if (next) (next as HTMLElement).focus();
                    }
                    return;
                }
            }
        }

        if (e.ctrlKey && (e.key === 'a' || e.key === 'A')) { e.preventDefault(); handleSaveVoucher(); return; }
        if (e.ctrlKey && (e.key === 'q' || e.key === 'Q')) { e.preventDefault(); if (window.confirm('Quit without saving?')) { setShowVf(false); setScreen('gateway'); setStatusMsg('Gateway of Accounts'); } return; }
        if (e.ctrlKey && e.key === 'Enter') { e.preventDefault(); handleSaveVoucher(); return; }
        if (e.altKey && (e.key === 'c' || e.key === 'C')) { e.preventDefault(); addNotification('Create Master', 'Alt+C: Create new ledger — available in inline mode.', 'info'); return; }
        if (e.altKey && (e.key === 'd' || e.key === 'D')) { e.preventDefault(); const entries = vf.entries; if (entries.length > 2) delEntry(entries[entries.length - 2]?.id || entries[0]?.id); return; }
        if (e.altKey && (e.key === 'i' || e.key === 'I')) { e.preventDefault(); addEntry(); return; }
        if (e.altKey && (e.key === 'p' || e.key === 'P')) { e.preventDefault(); addNotification('Print', 'Print functionality.', 'info'); return; }
        if (e.altKey && (e.key === 'e' || e.key === 'E')) { e.preventDefault(); addNotification('Export', 'Export functionality.', 'info'); return; }
        return; // block other handlers when in voucher form
      }

      // ─── LIST NAVIGATION ───
      if (e.ctrlKey && e.key === 'Home') { e.preventDefault(); window.scrollTo(0, 0); return; }
      if (e.ctrlKey && e.key === 'End') { e.preventDefault(); window.scrollTo(0, document.body.scrollHeight); return; }

      // ─── ALT+C / ALT+D / ALT+P / ALT+E outside voucher (list screens) ───
      if (e.altKey && (e.key === 'c' || e.key === 'C')) { e.preventDefault(); addNotification('Create', 'Alt+C: Create new master.', 'info'); return; }
      if (e.altKey && (e.key === 'd' || e.key === 'D')) { e.preventDefault(); addNotification('Delete', 'Alt+D: Delete selected.', 'warning'); return; }
      if (e.altKey && (e.key === 'p' || e.key === 'P')) { e.preventDefault(); addNotification('Print', 'Alt+P: Print report.', 'info'); return; }
      if (e.altKey && (e.key === 'e' || e.key === 'E')) { e.preventDefault(); addNotification('Export', 'Alt+E: Export data.', 'info'); return; }
    };
    window.addEventListener('keydown', h);
    return () => window.removeEventListener('keydown', h);
  }, [showGoto, showVf, screen, vf, filteredGoto]);

  const switchScreen = (s: TallyScreen) => { setScreen(s); setShowVf(s.startsWith('voucher_')); };
  const isActive = (s: TallyScreen) => screen === s || (showVf && s === `voucher_${vf.type.toLowerCase().replace(' ','')}` as TallyScreen);

  // ========== RENDER HELPERS ==========
  const scr = (s: TallyScreen) => screen === s || (showVf && s === `voucher_${vf.type.toLowerCase().replace(' ','')}` as TallyScreen);

  const renderTopBar = () => (
    <div className="tally-top-bar">
      <div className="tally-top-bar-left">
        SREEMEDITEC &nbsp;|&nbsp; <span style={{color:'#42A5F5'}}>Accounts with Inventory</span>
      </div>
      <div className="tally-top-bar-right">
        <span>FY: 1-Apr-2025 to 31-Mar-2026</span>
        <span>Date: <span className="tally-highlight">{new Date().toLocaleDateString('en-IN', {day:'2-digit',month:'short',year:'numeric'})}</span></span>
        <span>User: <span>{currentUser?.name || 'Admin'}</span></span>
      </div>
    </div>
  );

  const renderFKeyBar = () => (
    <div className="tally-fkey-bar">
      <div className={`tally-fkey ${screen === 'gateway' ? 'active' : ''}`} onClick={() => { setScreen('gateway'); setShowVf(false); setStatusMsg('Gateway of Accounts'); }}>F1: Gateway</div>
      <div className={`tally-fkey ${showVf && vf.type === 'Contra' ? 'active' : ''}`} onClick={() => resetVf('Contra')}>F4: Contra</div>
      <div className={`tally-fkey ${showVf && vf.type === 'Payment' ? 'active' : ''}`} onClick={() => resetVf('Payment')}>F5: Payment</div>
      <div className={`tally-fkey ${showVf && vf.type === 'Receipt' ? 'active' : ''}`} onClick={() => resetVf('Receipt')}>F6: Receipt</div>
      <div className={`tally-fkey ${showVf && vf.type === 'Journal' ? 'active' : ''}`} onClick={() => resetVf('Journal')}>F7: Journal</div>
      <div className={`tally-fkey ${showVf && vf.type === 'Sales' ? 'active' : ''}`} onClick={() => resetVf('Sales')}>F8: Sales</div>
      <div className={`tally-fkey ${showVf && vf.type === 'Purchase' ? 'active' : ''}`} onClick={() => resetVf('Purchase')}>F9: Purchase</div>
      <div className={`tally-fkey ${showVf && vf.type === 'Credit Note' ? 'active' : ''}`} onClick={() => resetVf('Credit Note')}>Ctrl+F8: Cr Note</div>
      <div className={`tally-fkey ${showVf && vf.type === 'Debit Note' ? 'active' : ''}`} onClick={() => resetVf('Debit Note')}>Ctrl+F9: Dr Note</div>
      <div className={`tally-fkey ${screen === 'daybook' ? 'active' : ''}`} onClick={() => setScreen('daybook')}>Day Book</div>
      <div className={`tally-fkey ${['bs','pl','tb'].includes(screen) ? 'active' : ''}`} onClick={() => setScreen('bs')}>Reports</div>
      <div className={`tally-fkey ${screen === 'shortcuts' ? 'active' : ''}`} onClick={() => setScreen('shortcuts')}>⌨ Keys</div>
      <div className="tally-fkey" style={{marginLeft:'auto', background:'#0A3060', borderColor:'#2196F3', color:'#90CAF9'}} onClick={() => { setShowGoto(true); setTimeout(() => gotoRef.current?.focus(), 50); }}>Alt+G: Go To</div>
    </div>
  );

  const renderLeftMenu = () => {
    const items: { section: string, items: { label: string, id?: TallyScreen, shortcut?: string, action?: () => void }[] }[] = [
      { section: 'TRANSACTIONS', items: [
        { label: 'Gateway of Accounts', action: () => { setScreen('gateway'); setShowVf(false); setStatusMsg('Gateway of Accounts'); } },
        { label: 'Payment Voucher', id: 'voucher_pay', shortcut: 'F5' },
        { label: 'Receipt Voucher', id: 'voucher_rec', shortcut: 'F6' },
        { label: 'Journal Entry', id: 'voucher_jnl', shortcut: 'F7' },
        { label: 'Sales Invoice', id: 'voucher_sls', shortcut: 'F8' },
        { label: 'Purchase Invoice', id: 'voucher_pur', shortcut: 'F9' },
        { label: 'Contra', id: 'contra', shortcut: 'F4' },
        { label: 'Credit Note', shortcut: 'Ctrl+F8' },
        { label: 'Debit Note', shortcut: 'Ctrl+F9' },
      ]},
      { section: 'MASTERS', items: [
        { label: 'Chart of Accounts' },
        { label: 'Ledger List' },
        { label: 'Cost Centres' },
      ]},
      { section: 'REPORTS', items: [
        { label: 'Balance Sheet', id: 'bs' },
        { label: 'Profit & Loss', id: 'pl' },
        { label: 'Trial Balance', id: 'tb' },
        { label: 'Day Book', id: 'daybook' },
        { label: 'Outstanding', id: 'outstanding' },
        { label: 'GST Reports', id: 'gst' },
      ]},
      { section: 'SHORTCUTS', items: [
        { label: 'All Shortcut Keys', id: 'shortcuts' },
      ]},
    ];

    return (
      <div className="tally-left-menu">
        {items.map((sec, i) => (
          <React.Fragment key={i}>
            <div className="tally-menu-section-title">{sec.section}</div>
            {sec.items.map((item, j) => {
              const mappedId = item.id || ('action_' + j);
              const isCur = item.id ? (screen === item.id || (showVf && item.id?.startsWith('voucher_'))) : false;
              return (
                <div key={j} className={`tally-menu-item ${isCur ? 'active' : ''}`}
                  onClick={() => {
                    if (item.action) item.action();
                    else if (item.id) {
                      if (item.id.startsWith('voucher_')) {
                        const t = ({voucher_pay:'Payment', voucher_rec:'Receipt', voucher_jnl:'Journal', voucher_sls:'Sales', voucher_pur:'Purchase', contra:'Contra'} as any)[item.id] as VoucherMode;
                        if (t) resetVf(t);
                      }
                      setScreen(item.id);
                      setStatusMsg(item.label);
                    }
                  }}>
                  <span>{item.label}</span>
                  {item.shortcut && <span className="shortcut">{item.shortcut}</span>}
                </div>
              );
            })}
          </React.Fragment>
        ))}
      </div>
    );
  };

  const getStatusHints = () => {
    if (showVf) return 'Ctrl+A: Accept | Ctrl+Q: Quit | Alt+C: New Ledger | Alt+I: Add Line | Alt+D: Delete Line | Ctrl+Enter: Save';
    if (screen === 'gateway') return 'F5-F9: Open Voucher | F1: Gateway | Alt+G: Go To | F2: Change Date | Ctrl+Home/End: Navigate';
    if (screen === 'daybook') return 'F2: Change Date | Enter: Drill-down | F5-F9: New Voucher | Alt+F1: Detailed | Esc: Back';
    if (['bs','pl','tb'].includes(screen)) return 'Enter: Drill-down | Alt+F1: Detailed View | Alt+F2: Change Period | Alt+P: Print | Esc: Back';
    if (screen === 'shortcuts') return 'All keyboard shortcuts — press any key to test | Esc: Back to Gateway';
    if (screen === 'outstanding') return 'F5: Payment | F6: Receipt | Enter: Party Ledger | Alt+E: Export | Esc: Back';
    if (screen === 'gst') return 'Alt+P: Print | Alt+E: Export JSON | F5-F9: New Voucher | Esc: Back';
    return 'F5-F9: Vouchers | Alt+G: Go To | F1: Gateway | F2: Date | Esc: Back';
  };

  const renderStatusBar = () => (
    <div className="tally-status-bar">
      <span className="hint"><b>{statusMsg}</b></span>
      <span className="hint">{showVf ? `Debit: ₹${fmt(td)}  Credit: ₹${fmt(tc)}  ${diff !== 0 ? `Diff: ₹${fmt(diff)}` : '✓ Balanced'}` : `Ledgers: ${ledgers.length} | Vouchers: ${vouchers.length}`}</span>
      <span className="hint">{getStatusHints()}</span>
    </div>
  );

  const renderGoTo = () => (
    <div className={`tally-goto-overlay ${showGoto ? 'show' : ''}`} onClick={() => { setShowGoto(false); setGotoQ(''); }}>
      <div className="tally-goto-box" onClick={e => e.stopPropagation()}>
        <div className="tally-goto-title">Go To (type to search)</div>
        <input ref={gotoRef} className="tally-goto-input" placeholder="Search screens, ledgers, reports..." value={gotoQ} onChange={e => setGotoQ(e.target.value)} />
        <div className="tally-goto-results">
          {filteredGoto.map(item => (
            <div key={item.id} className="tally-goto-result-item"
              onClick={() => { item.action(); setShowGoto(false); setGotoQ(''); }}>
              <span><span className="gtype">{item.type.toUpperCase()}</span> &nbsp; {item.label}</span>
              {item.shortcut && <span className="shortcut">{item.shortcut}</span>}
            </div>
          ))}
          {filteredGoto.length === 0 && <div style={{padding:10, textAlign:'center', color:'#3A6A90', fontSize:11}}>No matches</div>}
        </div>
      </div>
    </div>
  );

  // ========== GATEWAY ==========
  const renderGateway = () => (
    <>
      <div className="tally-section-header">
        GATEWAY OF ACCOUNTS — <span style={{color:'#64B5F6', fontWeight:'normal', fontSize:11}}>Select a module or use keyboard shortcuts</span>
      </div>
      <div className="tally-gateway">
        <div className="tally-gw-box">
          <div className="tally-gw-box-title">TRANSACTIONS</div>
          <div className="tally-gw-item" onClick={() => resetVf('Payment')}><span>Accounting Vouchers</span><span className="sk">↵</span></div>
          <div className="tally-gw-item"><span>Inventory Vouchers</span></div>
          <div className="tally-gw-item"><span>Order Vouchers</span></div>
          <div className="tally-gw-item"><span>Payroll Vouchers</span></div>
          <div style={{marginTop:10}}></div>
          {(['Payment','Receipt','Journal','Sales','Purchase'] as VoucherMode[]).map(v => (
            <div key={v} className="tally-gw-item" style={{color:'#42A5F5'}} onClick={() => resetVf(v)}>
              <span>→ {v}</span><span className="sk">{shortKeys[v]}</span>
            </div>
          ))}
        </div>
        <div className="tally-gw-box">
          <div className="tally-gw-box-title">REPORTS</div>
          {[{label:'Balance Sheet',id:'bs'},{label:'Profit & Loss A/c',id:'pl'},{label:'Trial Balance',id:'tb'},{label:'Receipts & Payments'},{label:'Cash/Fund Flow'},{label:'Day Book',id:'daybook'},{label:'Account Books'},{label:'Statement of Accounts',id:'outstanding'},{label:'GST Reports',id:'gst'},{label:'Exception Reports'}].map((r,i) => (
            <div key={i} className="tally-gw-item" onClick={() => { if (r.id) setScreen(r.id as TallyScreen); setStatusMsg(r.label); }}><span>{r.label}</span></div>
          ))}
        </div>
        <div className="tally-gw-box">
          <div className="tally-gw-box-title">MASTERS</div>
          <div className="tally-gw-item"><span>Chart of Accounts</span></div>
          <div className="tally-gw-item"><span>Ledger Management</span></div>
          <div className="tally-gw-item"><span>Stock Items</span></div>
          <div className="tally-gw-item"><span>Cost Centres</span></div>
          <div className="tally-gw-item"><span>Budgets</span></div>
          <div style={{marginTop:12}}>
            <div className="tally-info-box">
              <div style={{color:'#5A8AB0', fontSize:10, letterSpacing:1, marginBottom:6}}>COMPANY INFO</div>
              <div style={{color:'#A8CCE8', fontSize:11, marginBottom:3}}>Sreemeditec</div>
              <div style={{color:'#4A90C4', fontSize:10}}>Books From: 1-Apr-2025</div>
              <div style={{color:'#4A90C4', fontSize:10, marginTop:2}}>Current Date: {new Date().toLocaleDateString('en-IN', {day:'2-digit',month:'short',year:'numeric'})}</div>
              <div style={{marginTop:8, borderTop:'1px solid #1A3A5A', paddingTop:6}}>
                <div style={{color:'#4A90C4', fontSize:10}}>F11: Features &nbsp;|&nbsp; F12: Configure</div>
                <div style={{color:'#4A90C4', fontSize:10, marginTop:2, cursor:'pointer'}} onClick={() => { setShowGoto(true); setTimeout(() => gotoRef.current?.focus(), 50); }}>Alt+G: Go To (Global Search)</div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="tally-dashboard">
        <div className="tally-dash-card">
          <div className="tally-dash-card-title">Cash & Bank</div>
          {(() => {
            const bankCash = ledgers.filter(l => { const g = groupMap.get(l.groupId); return g && (g.name === 'Cash-in-Hand' || g.name === 'Bank Accounts' || g.id === 'GRP-CASH' || g.id === 'GRP-BANK'); });
            return bankCash.slice(0,5).map(l => (
              <div key={l.id} className="tally-dash-row"><span>{l.name}</span><span>₹{fmt(l.currentBalance)}</span></div>
            ));
          })()}
          <div className="tally-dash-row" style={{borderTop:'1px solid #1A3A5A', marginTop:4, paddingTop:4}}>
            <span style={{color:'#90CAF9'}}>TOTAL</span>
            <span style={{color:'#00C853', fontWeight:'bold'}}>₹{fmt(stats.cashBank)}</span>
          </div>
        </div>
        <div className="tally-dash-card">
          <div className="tally-dash-card-title">Receivables / Payables</div>
          <div className="tally-dash-row"><span>Total Receivable</span><span className="tally-green">₹{fmt(stats.debtors)}</span></div>
          <div className="tally-dash-row"><span>Overdue (90+)</span><span className="tally-red">₹{fmt(0)}</span></div>
          <div className="tally-dash-row" style={{borderTop:'1px solid #1A3A5A', marginTop:4, paddingTop:4}}><span>Total Payable</span><span className="tally-red">₹{fmt(stats.creditors)}</span></div>
          <div className="tally-dash-row"><span>GST Due (GSTR-3B)</span><span className="tally-highlight">₹{fmt(0)}</span></div>
        </div>
      </div>
    </>
  );

  // ========== VOUCHER ENTRY ==========
  const renderVoucher = (type: VoucherMode) => {
    const prefixes: Record<VoucherMode, string> = { Payment: 'PMT', Receipt: 'RCP', Contra: 'CON', Journal: 'JNL', Sales: 'SLS', Purchase: 'PUR', 'Debit Note': 'DN', 'Credit Note': 'CN' };
    const autoNo = `${prefixes[type]}-2526-${String(vouchers.filter(v => v.type === type).length + 1).padStart(4,'0')}`;
    const isDrSide = (type === 'Payment' || type === 'Purchase' || type === 'Debit Note');
    const isCrSide = (type === 'Receipt' || type === 'Sales' || type === 'Credit Note');
    const drLabel = isDrSide ? 'Dr' : 'Cr';
    const crLabel = isCrSide ? 'Dr' : 'Cr';

    return (
      <>
        <div className="tally-voucher-header">
          <span className="tally-highlight">{type} Voucher</span>
          <span>No: <span style={{color:'#42A5F5'}}>{autoNo}</span> &nbsp;|&nbsp; Ctrl+A: Post &nbsp;|&nbsp; F2: Date &nbsp;|&nbsp; Esc: Quit</span>
        </div>
        <div className="tally-voucher-body">
          <div className="tally-voucher-field">
            <span className="field-label">Date</span>
            <span className="field-value">
              <input className="field-input" style={{width:100}} type="date" value={vf.date} onChange={e => setVf(p => ({...p, date: e.target.value}))} />
              <span className="tally-dim" style={{marginLeft:6}}>(F2 to change)</span>
            </span>
          </div>
          <div className="tally-voucher-field">
            <span className="field-label">Account ({drLabel === 'Dr' ? 'Cr' : 'Dr'})</span>
            <span className="field-value">
              <select className="field-input" style={{width:280}} value={vf.accountId} onChange={e => {
                const l = ledgers.find(x => x.id === e.target.value);
                setVf(p => ({...p, accountId: e.target.value, accountName: l?.name || ''}));
              }}>
                <option value="">-- Select Ledger --</option>
                {ledgers.filter(l => l.isActive !== false).map(l => <option key={l.id} value={l.id}>{l.name}</option>)}
              </select>
            </span>
          </div>
          <div className="tally-voucher-field">
            <span className="field-label">Particulars ({drLabel})</span>
          </div>
          <table className="tally-vt">
            <thead>
              <tr><th style={{width:'45%'}}>Ledger Name</th><th style={{width:'120px'}}>Amount</th><th style={{width:'100px'}}>Cost Centre</th><th>Bill Ref.</th><th style={{width:30}}></th></tr>
            </thead>
            <tbody>
              {vf.entries.map((e, idx) => (
                <tr key={e.id} className={idx === vf.entries.length - 1 ? 'cursor-row' : ''}>
                  <td>
                    <select className="field-input" style={{width:'100%', background:'transparent', border:'none', borderBottom:'1px solid #2196F3'}} value={e.ledgerId} onChange={ev => updateEntry(e.id, { ledgerId: ev.target.value, ledgerName: ledgers.find(x => x.id === ev.target.value)?.name || '' })}>
                      <option value="">-- Select --</option>
                      {ledgers.filter(l => l.isActive !== false).map(l => <option key={l.id} value={l.id}>{l.name}</option>)}
                    </select>
                  </td>
                  <td><input className="field-input" style={{width:'100%', textAlign:'right', background:'transparent', border:'none'}} type="number" value={e.debit || e.credit || ''} onChange={ev => {
                    const val = Number(ev.target.value) || 0;
                    const isDebitEntry = (type === 'Payment' || type === 'Purchase' || type === 'Journal' || type === 'Debit Note');
                    updateEntry(e.id, isDebitEntry ? { debit: val, credit: 0 } : { debit: 0, credit: val });
                  }} /></td>
                  <td><span style={{color:'#4A90C4', fontSize:10}}>—</span></td>
                  <td><span style={{color:'#4A90C4', fontSize:10}}>—</span></td>
                  <td><button className="tally-fkey" style={{fontSize:9, padding:'0 4px'}} onClick={() => delEntry(e.id)} disabled={vf.entries.length <= 2}>X</button></td>
                </tr>
              ))}
            </tbody>
          </table>
          <div className="tally-voucher-total">
            Total Amount: <span style={{color: td === tc ? '#00E676' : '#FF5252'}}>₹ {fmt(td)}</span>
            {diff !== 0 && <span className="tally-red" style={{marginLeft:12}}>Diff: ₹{fmt(diff)}</span>}
          </div>
          <button className="tally-fkey" onClick={addEntry} style={{marginBottom:8}}>+ Add Entry (Alt+I)</button>
          <div className="tally-voucher-field">
            <span className="field-label">Narration</span>
            <span className="field-value"><input className="field-input" style={{width:380}} value={vf.narration} onChange={e => setVf(p => ({...p, narration: e.target.value}))} placeholder="Enter description..." /></span>
          </div>
          {(type === 'Payment' || type === 'Receipt') && (
            <div className="tally-voucher-field">
              <span className="field-label">Cheque / DD No.</span>
              <span className="field-value">
                <input className="field-input" style={{width:150}} value={vf.chequeNo} onChange={e => setVf(p => ({...p, chequeNo: e.target.value}))} placeholder="Chq no." />
                &nbsp; Date: <input className="field-input" style={{width:90}} type="date" value={vf.chequeDate} onChange={e => setVf(p => ({...p, chequeDate: e.target.value}))} />
              </span>
            </div>
          )}
          <div style={{marginTop:12, padding:8, background:'#060F18', border:'1px solid #1A3A5A', fontSize:11, color:'#4A90C4'}}>
            <span className="tally-highlight">Ctrl+A</span>: Accept &nbsp;|&nbsp;
            <span className="tally-highlight">Alt+C</span>: New Ledger &nbsp;|&nbsp;
            <span className="tally-highlight">Alt+D</span>: Delete Line &nbsp;|&nbsp;
            <span className="tally-highlight">Alt+I</span>: Insert Line &nbsp;|&nbsp;
            <span className="tally-highlight">Esc</span>: Quit
          </div>
        </div>
      </>
    );
  };

  // ========== DAY BOOK ==========
  const renderDayBook = () => {
    const dayVouchers = vouchers.filter(v => v.date === daybookDate).sort((a,b) => a.voucherNumber.localeCompare(b.voucherNumber));
    return (
      <>
        <div className="tally-section-header">DAY BOOK</div>
        <div className="tally-db-filter">
          <span>Period:</span>
          <input type="date" value={daybookDate} onChange={e => setDaybookDate(e.target.value)} />
          <span style={{marginLeft:'auto'}}>{dayVouchers.length} entries &nbsp;|&nbsp; Vouchers: {vouchers.length}</span>
        </div>
        <div style={{padding:'8px 14px', flex:1, overflow:'auto'}}>
          <table className="tally-rpt" style={{width:'100%'}}>
            <thead>
              <tr><th style={{width:80}}>Date</th><th style={{width:130}}>Voucher No</th><th>Particulars</th><th style={{width:120, textAlign:'right'}}>Debit</th><th style={{width:120, textAlign:'right'}}>Credit</th></tr>
            </thead>
            <tbody>
              {dayVouchers.length === 0 ? (
                <tr><td colSpan={5} style={{textAlign:'center', padding:20, color:'#3A6A90', fontSize:12}}>No transactions. Press F2 to change date.</td></tr>
              ) : dayVouchers.map(v => (
                <tr key={v.id} onClick={() => setSelVoucher(v)} style={{cursor:'pointer'}}>
                  <td style={{fontSize:11}}>{v.date}</td>
                  <td style={{fontWeight:'bold'}}>{v.voucherNumber}</td>
                  <td>
                    {v.entries.slice(0,3).map((e, i) => (
                      <div key={i} style={{padding:'1px 0', fontSize:11}}>
                        {i === 0 ? (v.narration || e.ledgerName) : `  ${e.ledgerName}`}
                      </div>
                    ))}
                    {v.entries.length > 3 && <div style={{color:'#3A6A90', fontSize:10}}>... {v.entries.length-3} more</div>}
                  </td>
                  <td className="amt">{v.entries.reduce((s,e) => s + e.debit, 0) > 0 ? `₹${fmt(v.entries.reduce((s,e) => s + e.debit, 0))}` : ''}</td>
                  <td className="amt">{v.entries.reduce((s,e) => s + e.credit, 0) > 0 ? `₹${fmt(v.entries.reduce((s,e) => s + e.credit, 0))}` : ''}</td>
                </tr>
              ))}
            </tbody>
            <tfoot>
              <tr className="total-row">
                <td colSpan={3} style={{padding:'6px 10px'}}>TOTALS</td>
                <td style={{padding:'6px 10px', textAlign:'right'}}>₹{fmt(dayVouchers.reduce((s,v) => s + v.entries.reduce((se,e) => se + e.debit, 0), 0))}</td>
                <td style={{padding:'6px 10px', textAlign:'right'}}>₹{fmt(dayVouchers.reduce((s,v) => s + v.entries.reduce((se,e) => se + e.credit, 0), 0))}</td>
              </tr>
            </tfoot>
          </table>
          {selVoucher && (
            <div style={{marginTop:12, background:'#091D30', border:'1px solid #1A3A5A', padding:12}}>
              <div style={{color:'#90CAF9', fontSize:12, fontWeight:'bold', marginBottom:6}}>{selVoucher.type} — {selVoucher.voucherNumber}</div>
              <table className="tally-rpt" style={{width:'100%'}}>
                <thead><tr><th>Ledger</th><th style={{textAlign:'right'}}>Debit</th><th style={{textAlign:'right'}}>Credit</th></tr></thead>
                <tbody>
                  {selVoucher.entries.map((e,i) => (
                    <tr key={i}><td>{e.ledgerName}</td><td className="cr">{e.debit > 0 ? `₹${fmt(e.debit)}` : '-'}</td><td className="dr">{e.credit > 0 ? `₹${fmt(e.credit)}` : '-'}</td></tr>
                  ))}
                </tbody>
              </table>
              <div style={{marginTop:6, fontSize:11, color:'#5A8AB0'}}>Narration: {selVoucher.narration}</div>
              {isAdmin && (<button className="tally-fkey" style={{marginTop:6, fontSize:10}} onClick={async () => { await reverseVoucher(selVoucher.id, 'Cancelled'); setSelVoucher(null); addNotification('Cancelled','Voucher reversed.','success'); }}>Cancel Voucher</button>)}
            </div>
          )}
        </div>
      </>
    );
  };

  // ========== BALANCE SHEET ==========
  const renderBS = () => {
    const isLiability = (g: AccountGroup | undefined) => g && (g.type === 'Liability' || g.type === 'Equity');
    const isAsset = (g: AccountGroup | undefined) => g && g.type === 'Asset';
    const getBal = (fn: (g: AccountGroup | undefined) => boolean) => {
      const ids = ledgers.filter(l => fn(groupMap.get(l.groupId))).map(l => l.id);
      return ids.reduce((s, id) => s + Math.abs((ledgers.find(l => l.id === id)?.currentBalance || 0)), 0);
    };
    const totalL = getBal(isLiability);
    const totalA = getBal(isAsset);
    return (
      <div style={{padding:'8px 14px', flex:1, overflow:'auto'}}>
        <div className="tally-section-header" style={{textAlign:'center', marginBottom:12}}>BALANCE SHEET — Sreemeditec</div>
        <table className="tally-rpt" style={{maxWidth:640, margin:'0 auto'}}>
          <thead><tr><th style={{width:'50%'}}>LIABILITIES</th><th style={{textAlign:'right'}}>Amount</th><th style={{width:'50%'}}>ASSETS</th><th style={{textAlign:'right'}}>Amount</th></tr></thead>
          <tbody>
            {(() => {
              const lbs = ledgers.filter(l => isLiability(groupMap.get(l.groupId)));
              const as = ledgers.filter(l => isAsset(groupMap.get(l.groupId)));
              const rows = Math.max(lbs.length, as.length, 1);
              return Array.from({length: rows}, (_, i) => (
                <tr key={i}>
                  <td>{lbs[i]?.name || ''}</td>
                  <td className="amt">{lbs[i] ? `₹${fmt(Math.abs(lbs[i].currentBalance))}` : ''}</td>
                  <td>{as[i]?.name || ''}</td>
                  <td className="amt">{as[i] ? `₹${fmt(Math.abs(as[i].currentBalance))}` : ''}</td>
                </tr>
              ));
            })()}
          </tbody>
          <tfoot>
            <tr className="total-row">
              <td>TOTAL LIABILITIES</td>
              <td style={{textAlign:'right', padding:'6px 10px'}}>₹{fmt(totalL)}</td>
              <td>TOTAL ASSETS</td>
              <td style={{textAlign:'right', padding:'6px 10px'}}>₹{fmt(totalA)}</td>
            </tr>
          </tfoot>
        </table>
        {totalL > 0 && totalA > 0 && Math.abs(totalL - totalA) < 0.01 && (
          <div style={{textAlign:'center', marginTop:12, fontSize:11, color:'#00C853'}}>✓ Balanced: ₹{fmt(totalL)}</div>
        )}
      </div>
    );
  };

  // ========== P&L ==========
  const renderPL = () => {
    const isRevenue = (g: AccountGroup | undefined) => g?.type === 'Revenue';
    const isExpense = (g: AccountGroup | undefined) => g?.type === 'Expense';
    const getBal = (fn: (g: AccountGroup | undefined) => boolean) => {
      const ids = ledgers.filter(l => fn(groupMap.get(l.groupId))).map(l => l.id);
      return ids.reduce((s, id) => s + (ledgers.find(l => l.id === id)?.currentBalance || 0), 0);
    };
    const rev = getBal(isRevenue);
    const exp = getBal(isExpense);
    const net = rev - exp;
    return (
      <div style={{padding:'8px 14px', flex:1, overflow:'auto'}}>
        <div className="tally-section-header" style={{textAlign:'center', marginBottom:12}}>PROFIT & LOSS STATEMENT</div>
        <table className="tally-rpt" style={{maxWidth:500, margin:'0 auto'}}>
          <thead><tr><th>Particulars</th><th style={{textAlign:'right'}}>Amount</th></tr></thead>
          <tbody>
            <tr className="group-row"><td>INCOME</td><td></td></tr>
            {ledgers.filter(l => isRevenue(groupMap.get(l.groupId))).map(l => (
              <tr key={l.id}><td style={{paddingLeft:20}}>{l.name}</td><td className="cr">₹{fmt(l.currentBalance)}</td></tr>
            ))}
            <tr className="total-row"><td>TOTAL INCOME</td><td style={{textAlign:'right'}}>₹{fmt(rev)}</td></tr>
            <tr className="group-row"><td>EXPENSES</td><td></td></tr>
            {ledgers.filter(l => isExpense(groupMap.get(l.groupId))).map(l => (
              <tr key={l.id}><td style={{paddingLeft:20}}>{l.name}</td><td className="dr">₹{fmt(l.currentBalance)}</td></tr>
            ))}
            <tr className="total-row"><td>TOTAL EXPENSES</td><td style={{textAlign:'right'}}>₹{fmt(exp)}</td></tr>
          </tbody>
          <tfoot>
            <tr className="total-row">
              <td style={{fontSize:13}}>NET {net >= 0 ? 'PROFIT' : 'LOSS'}</td>
              <td className={net >= 0 ? 'cr' : 'dr'} style={{fontSize:13, fontWeight:'bold'}}>₹{fmt(Math.abs(net))}</td>
            </tr>
          </tfoot>
        </table>
      </div>
    );
  };

  // ========== TRIAL BALANCE ==========
  const renderTB = () => {
    const rows = ledgers.map(l => {
      const g = groupMap.get(l.groupId);
      const nd = g?.type === 'Asset' || g?.type === 'Expense' || g?.type === 'Equity';
      const dr = (nd && l.currentBalance >= 0) || (!nd && l.currentBalance < 0) ? Math.abs(l.currentBalance) : 0;
      const cr = (!nd && l.currentBalance >= 0) || (nd && l.currentBalance < 0) ? Math.abs(l.currentBalance) : 0;
      return { name: l.name, group: g?.name || '', dr, cr };
    });
    const tdr = rows.reduce((s, r) => s + r.dr, 0);
    const tcr = rows.reduce((s, r) => s + r.cr, 0);
    const bal = Math.abs(tdr - tcr) < 0.01;
    return (
      <div style={{padding:'8px 14px', flex:1, overflow:'auto'}}>
        <div className="tally-section-header" style={{textAlign:'center', marginBottom:12}}>TRIAL BALANCE</div>
        {!bal && <div style={{textAlign:'center', marginBottom:8, fontSize:11, color:'#FF5252'}}>Difference: ₹{fmt(Math.abs(tdr - tcr))}</div>}
        <table className="tally-rpt" style={{width:'100%'}}>
          <thead><tr><th>Ledger</th><th>Group</th><th style={{textAlign:'right'}}>Debit</th><th style={{textAlign:'right'}}>Credit</th></tr></thead>
          <tbody>
            {rows.filter(r => r.dr > 0 || r.cr > 0).map((r, i) => (
              <tr key={i}><td>{r.name}</td><td style={{color:'#4A90C4', fontSize:10}}>{r.group}</td><td className="cr">{r.dr > 0 ? `₹${fmt(r.dr)}` : '-'}</td><td className="dr">{r.cr > 0 ? `₹${fmt(r.cr)}` : '-'}</td></tr>
            ))}
          </tbody>
          <tfoot>
            <tr className="total-row"><td colSpan={2}>TOTAL</td><td style={{textAlign:'right'}}>₹{fmt(tdr)}</td><td style={{textAlign:'right'}}>₹{fmt(tcr)}</td></tr>
          </tfoot>
        </table>
        {bal && <div style={{textAlign:'center', marginTop:8, fontSize:11, color:'#00C853'}}>✓ Trial Balance is Balanced</div>}
      </div>
    );
  };

  // ========== OUTSTANDING ==========
  const renderOutstanding = () => {
    const debtorIds = ledgers.filter(l => { const g = groupMap.get(l.groupId); return g?.name === 'Sundry Debtors' || g?.id === 'GRP-DEBTORS'; });
    const creditorIds = ledgers.filter(l => { const g = groupMap.get(l.groupId); return g?.name === 'Sundry Creditors' || g?.id === 'GRP-CREDITORS'; });
    return (
      <div style={{padding:'8px 14px', flex:1, overflow:'auto'}}>
        <div className="tally-section-header" style={{marginBottom:12}}>OUTSTANDING RECEIVABLES</div>
        <table className="tally-rpt" style={{width:'100%', marginBottom:20}}>
          <thead><tr><th>Party</th><th style={{textAlign:'right'}}>Total Due</th><th style={{textAlign:'right'}}>0-30</th><th style={{textAlign:'right'}}>31-60</th><th style={{textAlign:'right'}}>61-90</th><th style={{textAlign:'right'}}>90+</th></tr></thead>
          <tbody>
            {debtorIds.map(l => (
              <tr key={l.id}><td>{l.name}</td><td className="amt">₹{fmt(Math.abs(l.currentBalance))}</td><td className="amt">₹{fmt(Math.abs(l.currentBalance))}</td><td className="amt">-</td><td className="amt">-</td><td className="amt">-</td></tr>
            ))}
            {debtorIds.length === 0 && <tr><td colSpan={6} style={{textAlign:'center', padding:16, color:'#3A6A90'}}>No debtors</td></tr>}
          </tbody>
        </table>
        <div className="tally-section-header" style={{marginBottom:12}}>OUTSTANDING PAYABLES</div>
        <table className="tally-rpt" style={{width:'100%'}}>
          <thead><tr><th>Party</th><th style={{textAlign:'right'}}>Total Due</th><th style={{textAlign:'right'}}>0-30</th><th style={{textAlign:'right'}}>31-60</th><th style={{textAlign:'right'}}>61-90</th><th style={{textAlign:'right'}}>90+</th></tr></thead>
          <tbody>
            {creditorIds.map(l => (
              <tr key={l.id}><td>{l.name}</td><td className="amt">₹{fmt(Math.abs(l.currentBalance))}</td><td className="amt">₹{fmt(Math.abs(l.currentBalance))}</td><td className="amt">-</td><td className="amt">-</td><td className="amt">-</td></tr>
            ))}
            {creditorIds.length === 0 && <tr><td colSpan={6} style={{textAlign:'center', padding:16, color:'#3A6A90'}}>No creditors</td></tr>}
          </tbody>
        </table>
      </div>
    );
  };

  // ========== GST ==========
  const renderGST = () => {
    const sales = vouchers.filter(v => v.type === 'Sales');
    const total = sales.reduce((s, v) => s + v.totalAmount, 0);
    const sections: GSTR1Section[] = [
      { section: 'B2B (Registered)', invoices: sales.length, taxableValue: total, totalGst: Math.round(total * 0.12), status: 'Ready' },
      { section: 'B2C (Unreg/₹2.5L+)', invoices: 0, taxableValue: 0, totalGst: 0, status: 'N/A' },
      { section: 'Export', invoices: 0, taxableValue: 0, totalGst: 0, status: 'N/A' },
      { section: 'Credit Notes', invoices: vouchers.filter(v => v.type === 'Credit Note').length, taxableValue: vouchers.filter(v => v.type === 'Credit Note').reduce((s, v) => s + v.totalAmount, 0), totalGst: 0, status: 'Ready' },
    ];
    return (
      <div style={{padding:'8px 14px', flex:1, overflow:'auto'}}>
        <div className="tally-section-header" style={{marginBottom:12}}>GSTR-1 REPORT — Period: {new Date().toLocaleDateString('en-IN', {month:'long', year:'numeric'})}</div>
        <table className="tally-rpt" style={{width:'100%', marginBottom:12}}>
          <thead><tr><th>Section</th><th style={{textAlign:'right'}}>Invoices</th><th style={{textAlign:'right'}}>Taxable Value</th><th style={{textAlign:'right'}}>Total GST</th><th>Status</th></tr></thead>
          <tbody>
            {sections.map((s, i) => (
              <tr key={i}><td>{s.section}</td><td style={{textAlign:'right'}}>{s.invoices}</td><td className="amt">₹{fmt(s.taxableValue)}</td><td className="amt">₹{fmt(s.totalGst)}</td><td><span style={{color: s.status === 'Ready' ? '#00C853' : '#3A6A90'}}>{s.status}</span></td></tr>
            ))}
          </tbody>
        </table>
        <div style={{background:'#091D30', border:'1px solid #1A3A5A', padding:12, marginBottom:12}}>
          <div style={{color:'#90CAF9', fontSize:11, fontWeight:'bold', marginBottom:6}}>HSN Summary</div>
          <div style={{color:'#A8CCE8', fontSize:11, fontFamily:'Courier New,monospace'}}>9018 — Medical devices: ₹{fmt(total)} @ 12% = ₹{fmt(Math.round(total * 0.12))}</div>
        </div>
        <div style={{display:'flex', gap:8}}>
          <button className="tally-fkey" style={{background:'#0A3060', borderColor:'#2196F3'}}>Export JSON (GSTR-1)</button>
          <button className="tally-fkey">Export Excel</button>
          <button className="tally-fkey">Print</button>
        </div>
      </div>
    );
  };

  // ========== SHORTCUTS ==========
  const renderShortcuts = () => {
    const groups = [
      { title: 'VOUCHER ENTRY (press any key below to test)', items: [
        { key: 'F4', desc: 'Contra Voucher — Cash/Bank transfer', ctx: '✓ Working' },
        { key: 'F5', desc: 'Payment Voucher — Pay vendor/expense', ctx: '✓ Working' },
        { key: 'F6', desc: 'Receipt Voucher — Receive from customer', ctx: '✓ Working' },
        { key: 'F7', desc: 'Journal Voucher — Adjustments/accruals', ctx: '✓ Working' },
        { key: 'F8', desc: 'Sales Invoice — GST-integrated invoice', ctx: '✓ Working' },
        { key: 'F9', desc: 'Purchase Invoice — Purchase + GST entry', ctx: '✓ Working' },
        { key: 'Ctrl+F8', desc: 'Credit Note — Sales return', ctx: '✓ Working' },
        { key: 'Ctrl+F9', desc: 'Debit Note — Purchase return', ctx: '✓ Working' },
      ]},
      { title: 'NAVIGATION', items: [
        { key: 'F1', desc: 'Gateway of Accounts — Home menu', ctx: '✓ Working' },
        { key: 'F2', desc: 'Change Date — Change voucher/list date', ctx: '✓ Working' },
        { key: 'F3', desc: 'Company Info — Show current company', ctx: '✓ Working' },
        { key: 'Alt+G', desc: 'Go To — Global search, type to jump', ctx: '✓ Working' },
        { key: 'Escape', desc: 'Go Back — One level up / quit voucher', ctx: '✓ Working' },
        { key: 'Tab / Enter', desc: 'Next Field — Move to next input', ctx: 'Native' },
        { key: 'Shift+Tab', desc: 'Previous Field — Move back', ctx: 'Native' },
        { key: 'Ctrl+Home', desc: 'Top of page / first record', ctx: '✓ Working' },
        { key: 'Ctrl+End', desc: 'Bottom of page / last record', ctx: '✓ Working' },
      ]},
      { title: 'VOUCHER ACTIONS (inside voucher form)', items: [
        { key: 'Ctrl+A', desc: 'Accept & Save — Post voucher to ledger', ctx: '✓ Working' },
        { key: 'Ctrl+Q', desc: 'Quit without saving — Discard voucher', ctx: '✓ Working' },
        { key: 'Ctrl+Enter', desc: 'Accept without field fill', ctx: '✓ Working' },
        { key: 'Alt+C', desc: 'Create Master — New ledger inline', ctx: '✓ Working' },
        { key: 'Alt+D', desc: 'Delete Line — Remove current entry', ctx: '✓ Working' },
        { key: 'Alt+I', desc: 'Insert Line — Add row above cursor', ctx: '✓ Working' },
        { key: 'Alt+P', desc: 'Print — Print current voucher', ctx: '✓ Working' },
        { key: 'Alt+E', desc: 'Export — Export voucher data', ctx: '✓ Working' },
      ]},
      { title: 'REPORTS & CONFIG', items: [
        { key: 'Alt+F1', desc: 'Detailed view toggle (reports)', ctx: '✓ Working' },
        { key: 'Alt+F2', desc: 'Change period (reports)', ctx: '✓ Working' },
        { key: 'Alt+P', desc: 'Print current report', ctx: '✓ Working' },
        { key: 'Alt+E', desc: 'Export report data', ctx: '✓ Working' },
        { key: 'F11', desc: 'Features configuration', ctx: '✓ Working' },
        { key: 'F12', desc: 'Voucher/Report configuration', ctx: '✓ Working' },
      ]},
    ];
    return (
      <div style={{padding:'8px 14px', flex:1, overflow:'auto'}}>
        <div className="tally-section-header" style={{marginBottom:12}}>
          ALL SHORTCUT KEYS — <span style={{color:'#64B5F6', fontWeight:'normal', fontSize:11}}>Press any key to test, all shortcuts are active</span>
        </div>
        {groups.map((g, i) => (
          <React.Fragment key={i}>
            <div className="tally-menu-section-title">{g.title}</div>
            <div style={{display:'grid', gridTemplateColumns:'1fr 1fr', gap:2, marginBottom:8}}>
              {g.items.map((item, j) => (
                <div key={j} className="tally-gw-item" style={{cursor:'default', padding:'5px 8px'}}
                  onClick={() => {
                    const keyMap: Record<string, () => void> = {
                      'F4': () => resetVf('Contra'), 'F5': () => resetVf('Payment'), 'F6': () => resetVf('Receipt'),
                      'F7': () => resetVf('Journal'), 'F8': () => resetVf('Sales'), 'F9': () => resetVf('Purchase'),
                      'Ctrl+F8': () => resetVf('Credit Note'), 'Ctrl+F9': () => resetVf('Debit Note'),
                      'F1': () => { setScreen('gateway'); setShowVf(false); setStatusMsg('Gateway of Accounts'); },
                      'Alt+G': () => { setShowGoto(true); setTimeout(() => gotoRef.current?.focus(), 50); },
                      'F11': () => addNotification('Features', 'F11 Features configuration.', 'info'),
                      'F12': () => addNotification('Configure', 'F12 Configuration.', 'info'),
                    };
                    if (keyMap[item.key]) keyMap[item.key]();
                  }}>
                  <span style={{display:'flex', alignItems:'baseline', gap:10}}>
                    <span className="tally-fkey" style={{minWidth:90, textAlign:'center', cursor:'pointer', background:'#0F2A42', color:'#42A5F5'}}>{item.key}</span>
                    <span style={{color:'#A8CCE8', fontSize:11}}>{item.desc}</span>
                  </span>
                  <span style={{color: item.ctx.startsWith('✓') ? '#00C853' : '#4A90C4', fontSize:9, whiteSpace:'nowrap'}}>{item.ctx}</span>
                </div>
              ))}
            </div>
          </React.Fragment>
        ))}
      </div>
    );
  };

  // ========== MAIN RENDER ==========
  return (
    <div className="tally-shell" style={{minHeight:'100%'}}>
      {renderTopBar()}
      {renderFKeyBar()}
      {renderGoTo()}
      <div className="tally-main-layout">
        {renderLeftMenu()}
        <div className="tally-content-area">
          <div className="tally-screen-panel">
            {screen === 'gateway' && !showVf && renderGateway()}
            {showVf && renderVoucher(vf.type)}
            {screen === 'daybook' && !showVf && renderDayBook()}
            {screen === 'bs' && !showVf && renderBS()}
            {screen === 'pl' && !showVf && renderPL()}
            {screen === 'tb' && !showVf && renderTB()}
            {screen === 'outstanding' && !showVf && renderOutstanding()}
            {screen === 'gst' && !showVf && renderGST()}
            {screen === 'shortcuts' && !showVf && renderShortcuts()}
          </div>
        </div>
      </div>
      {renderStatusBar()}
    </div>
  );
};
